GO
CREATE DATABASE GIMNASIO_DB
GO

USE GIMNASIO_DB;
GO

CREATE TABLE SOCIO (
	id INT IDENTITY (1,1) PRIMARY KEY,
	nombre NVARCHAR(100) NOT NULL,
	telefono NVARCHAR (20),
	correo NVARCHAR(100) UNIQUE CHECK (
		correo LIKE '_%@_%._%'
	)
);


CREATE TABLE CLASE(
	id INT IDENTITY(1,1) PRIMARY KEY,
	id_entrenador INT NOT NULL,
	valor_de_clase DECIMAL(10,2),
	mensualidad DECIMAL(10,2)
);


CREATE TABLE ENTRENADOR (
    id INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(100) NOT NULL,
    correo NVARCHAR(100),
    especialidad NVARCHAR(100),
    sueldo DECIMAL(10,2)  
);


CREATE TABLE GRUPO_DE_CLASE (
    id INT IDENTITY(1,1) PRIMARY KEY,
    horario NVARCHAR(100),
    capacidad INT,
	id_clase INT
);


CREATE TABLE RESERVA (
  id INT IDENTITY(1,1) PRIMARY KEY,
  id_socio INT NOT NULL,
  id_grupo_de_clase INT NOT NULL
);


CREATE TABLE PAGO (
    id INT IDENTITY(1,1) PRIMARY KEY,
    id_socio INT NOT NULL,
    id_grupo_de_clase INT NULL,        
    id_entrenador INT NULL,     
    monto DECIMAL(10,2) NOT NULL,
    metodo_pago NVARCHAR(50) NULL,
    fecha_y_hora DATETIME DEFAULT GETDATE()
);
GO


ALTER TABLE RESERVA
ADD CONSTRAINT FK_RESERVA_SOCIO
FOREIGN KEY (id_socio)
REFERENCES SOCIO(id);

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RESERVA_GRUPODECLASE
FOREIGN KEY (id_grupo_de_clase)
REFERENCES GRUPO_DE_CLASE(id);

ALTER TABLE PAGO
ADD CONSTRAINT FK_PAGO_GRUPODECLASE
FOREIGN KEY (id_grupo_de_clase)
REFERENCES GRUPO_DE_CLASE (id);

ALTER TABLE PAGO
ADD CONSTRAINT FK_PAGO_ENTRENADOR
FOREIGN KEY (id_entrenador)
REFERENCES ENTRENADOR(id);

ALTER TABLE PAGO
ADD CONSTRAINT FK_PAGO_SOCIO
FOREIGN KEY (id_socio)
REFERENCES SOCIO(id)


ALTER TABLE CLASE
ADD CONSTRAINT FK_CLASE_ENTRENADOR
FOREIGN KEY (id_entrenador)
REFERENCES ENTRENADOR(id);

ALTER TABLE GRUPO_DE_CLASE
ADD CONSTRAINT FK_GRUPODECLASE_CLASE
FOREIGN KEY (id_clase)
REFERENCES CLASE(id)

